### ISSUE TITLE
Incorrect parsing image URI

### ISSUE THREAD

**Issue by crosspath** [jjyr/minidown#11]
I have image URI containing spaces

```
![график](Глава 2/Рисунки/Нагрузка.png)
```

Minidown renders it like

```
<p><img src="Глава" alt="график"></img></p>
```

dropping all between space and closing paranthesis.

Replacing space to "%20" in markdown file looks ugly but Minidown renders it correctly:

```
![график](Глава%202/Рисунки/Нагрузка.png)
<p><img src="Глава%202/Рисунки/Нагрузка.png" alt="график"></img></p>
```

**Comment by jjyr** [comment]
Hi, maintain of this project was stopped, you can try fix it and pr to this repo or try other awesome markdown libraries like https://github.com/bhollis/maruku https://github.com/davidfstr/rdiscount
